name: Keep Sites Awake

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Sites
        run: |
          curl -L https://forminclusaocolaboraores-ewnykkvf9vn9b8qpvdpdyr.streamlit.app/
          curl -L https://sistem-av-escritorio-qqlm4x6nq4drkkhbupxvcw.streamlit.app/
          curl -L https://sistema-av-crud-e2wzacxchywdxbpdba3jzl.streamlit.app/
          curl -L https://sistema-av-obra-qnma5exfzyya8rkdfkyq7i.streamlit.app/
          curl -L https://sistema-rh-saldo-de-ferias.streamlit.app/
          