name: Keep Sites Awake

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Streamlit App
        run: |
          curl -L \
            -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64)" \
            --max-redirs 10 \
            --connect-timeout 30 \
            --silent --show-error \
            https://forminclusaocolaboraores-ewnykkvf9vn9b8qpvdpdyr.streamlit.app/
